### ISSUE TITLE
Remove jQuery as a dependency

### ISSUE THREAD

**Issue by ozten** [mozilla/repotheweb#1]
jQuery will let us write the shim quickly, but should probably be removed, if cross-browser JS isn't to hard without it.

**Comment by alcinnz** [comment]
I looked into this, and the tough bit is the ready. However there is https://github.com/airportyh/onready/blob/master/onready.js which provides us with that and nothing else. 

As for the a links, it would be much more efficient and reliable (with DHTML) to use the equivalent of $.fn.delegate (i.e. Less memory and handles ny added links). This actually turns out to be easier in a no jQuery environment than classic events as http://cherny.com/webdev/70/javascript-event-delegation-and-event-hanlders discusses.

**Comment by alcinnz** [comment]
Actually, I don't think we'd need ready, the document would exist already. 

All we'd do to touch the DOM is (derived from the blog in the last post):

```
document.onclick = function(evt) {
  evt |= window.event;
  t = e.target | e.srcElement;
  simulate_rph.call(t, evt);
}
```

Perhaps later add more thorough support, as in frames and maybe forms. This could be achieved using a for/in loop.
